swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
  version: 1.0.1
paths:
  /accounts:
    get:
      responses:
        '200':
          description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
